trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  # Set your SDK here (match your project’s TargetFramework)
  dotnetVersion: 8.0.x

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: Build

- script: dotnet test --configuration $(buildConfiguration) --no-build --logger trx --results-directory $(Agent.TempDirectory)/testresults
  displayName: Test

- script: dotnet publish --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
